permissions:
  contents: write

name: release.yml
on:
  pull_request:
    branches:
      - ovm-next

jobs:
  build-macos:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: 'actions/checkout@v5'
        with:
          lfs: 'true'

      - name: Set up Go
        uses: 'actions/setup-go@v5'
        with:
          go-version: '1.25.5'

      - name: Install dependencies
        run: brew tap slp/krun && brew install golangci-lint libarchive e2fsprogs virglrenderer libepoxy molten-vk

      - name: Build
        run: go run scripts/build.go

      - name: Upload artifact
        uses: 'actions/upload-artifact@v4'
        with:
          name: ovm-darwin
          path: |
            ovm-*.tar.gz
          if-no-files-found: error
          overwrite: true

  build-linux:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: 'actions/checkout@v5'
        with:
          lfs: 'true'

      - name: Set up Go
        uses: 'actions/setup-go@v5'
        with:
          go-version: '1.25.5'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget patchelf libarchive-tools libarchive-dev libext2fs-dev libblkid-dev uuid-dev zstd
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Build
        run: go run scripts/build.go

      - name: Upload artifact
        uses: 'actions/upload-artifact@v4'
        with:
          name: ovm-linux
          path: |
            ovm-*.tar.gz
          if-no-files-found: error
          overwrite: true
